import sys
import os


def get_data_path(is_executing_from_kiwoom=False):
    """
    get data absolute path depending on whether executing .py script or binary file made by PyInstaller
    """
    try:
        # PyInstaller creates a temp folder and stores path in _MEIPASS
        # refer to https://stackoverflow.com/questions/51060894/adding-a-data-file-in-pyinstaller-using-the-onefile-option
        base_path = sys._MEIPASS
    except:
        if is_executing_from_kiwoom:
            base_path = os.path.abspath("./kiwoom")
        else:
            base_path = os.path.abspath(".")
    return base_path


def is_exe_file():
    """
    conditional checking whether we are running exe file generated by PyInstaller
    """
    is_exe_executing = False
    try:
        test = sys._MEIPASS
        is_exe_executing = True
    except:
        is_exe_executing = False
    return is_exe_executing


def get_config_path(is_executing_from_kiwoom=False):
    """
    get config file path
    """
    if is_executing_from_kiwoom:
        base_path = os.path.abspath("./kiwoom")
    else:
        base_path = os.path.abspath(".")
    return base_path
